[app]
  name = "libroverse"

[build]
  image = ""

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls","http"]
    port = 443

  [services.healthchecks]
    protocol = "http"
    path = "/"
    interval = 10000
    timeout = 2000
    grace_period = 30000
    method = "GET"
